version: '3'

services:
  apache:
    image: httpd:2.4-alpine
    working_dir: /var/www/
    volumes:
      - ./source:/var/www
      - ./containers/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    ports:
      - 80:80

  php:
    build: containers/php-fpm
    volumes:
      - ./source:/var/www

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql