version: '3.7'

services:

  apache:
    image: httpd:2.4-alpine
    working_dir: /var/www/
    volumes:
      - ./source:/var/www
      - ./containers/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    ports:
      - 80:80

  php:
    build:
      context: containers/php-fpm
      args:
        HOST_USER_ID: ${HOST_USER_ID}
        HOST_GROUP_ID: ${HOST_GROUP_ID}
        HOST_USER_NAME: ${HOST_USER_NAME}
        HOST_GROUP_NAME: ${HOST_GROUP_NAME}
    volumes:
      - ./source:/var/www
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql

  node:
    image: "node:8"
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    working_dir: /var/www
    volumes:
      - ./source:/var/www