version: '3.7'

services:

  apache:
    build:
      context: containers/httpd
    working_dir: /var/www/
    volumes:
      - ./source:/var/www
    ports:
      - 80:80

  php:
    build:
      context: containers/php-fpm
      args:
        HOST_USER_ID: ${HOST_USER_ID}
        HOST_GROUP_ID: ${HOST_GROUP_ID}
        HOST_USER_NAME: ${HOST_USER_NAME}
        HOST_GROUP_NAME: ${HOST_GROUP_NAME}
    volumes:
      - ./source:/var/www
      - ./data/php:/var/sync
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    depends_on:
      - mysql
      - mailhog

  mysql:
    image: mysql:5.7
    restart: always
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  node:
    image: "node:8"
    user: ${HOST_USER_ID}:${HOST_GROUP_ID}
    working_dir: /var/www
    volumes:
      - ./source:/var/www